### ISSUE TITLE
Plugin incompatible with gradle 1.7-rc-2

### ISSUE THREAD

**Issue by smgeorge99** [TrigonicSolutions/gradle-rpm-plugin#42] opened 2013-07-30 17:47 UTC
My project has been using this plugin since we were on gradle 1.5.  Our project has since upgraded to gradle 1.6, and it works fine there as well.  However, when I tried to run it against gradle 1.7-rc-2, I get the following exception:

```
Caused by: org.gradle.api.tasks.TaskInstantiationException: Could not create task of type 'Rpm'.
        at org.gradle.api.internal.project.taskfactory.TaskFactory$1.call(TaskFactory.java:115)
        at org.gradle.api.internal.project.taskfactory.TaskFactory$1.call(TaskFactory.java:110)
        at org.gradle.api.internal.AbstractTask.injectIntoNewInstance(AbstractTask.java:145)
        at org.gradle.api.internal.project.taskfactory.TaskFactory.createTaskObject(TaskFactory.java:110)
        at org.gradle.api.internal.project.taskfactory.TaskFactory.createTask(TaskFactory.java:70)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory.createTask(AnnotationProcessingTa
skFactory.java:100)
        at org.gradle.api.internal.project.taskfactory.DependencyAutoWireTaskFactory.createTask(DependencyAutoWireTaskFa
ctory.java:39)
        at org.gradle.api.internal.tasks.DefaultTaskContainer.create(DefaultTaskContainer.java:55)
        at org.gradle.api.internal.project.AbstractProject.task(AbstractProject.java:912)
        at org.gradle.api.internal.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:248)
        at org.gradle.api.internal.BeanDynamicObject.invokeMethod(BeanDynamicObject.java:136)
        at org.gradle.api.internal.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:147)
        at org.gradle.groovy.scripts.BasicScript.methodMissing(BasicScript.java:83)
        at build_1q0vdf37kt70qi5s07ijhsm3d9.run(C:\Promontory\BAP\software\services\build.gradle:50)
        at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory
.java:52)
        ... 51 more
Caused by: java.lang.NoSuchMethodError: org.gradle.api.internal.file.copy.CopyActionImpl.<init>(Lorg/gradle/api/internal
/file/FileResolver;Lorg/gradle/api/internal/file/copy/CopySpecVisitor;)V
        at com.trigonic.gradle.plugins.rpm.Rpm$RpmCopyAction.<init>(Rpm.groovy:154)
        at com.trigonic.gradle.plugins.rpm.Rpm.<init>(Rpm.groovy:62)
        at com.trigonic.gradle.plugins.rpm.Rpm_Decorated.<init>(Unknown Source)
        at org.gradle.api.internal.DependencyInjectingInstantiator.newInstance(DependencyInjectingInstantiator.java:62)
        at org.gradle.api.internal.ClassGeneratorBackedInstantiator.newInstance(ClassGeneratorBackedInstantiator.java:36
)
        at org.gradle.api.internal.project.taskfactory.TaskFactory$1.call(TaskFactory.java:113)
        ... 65 more
```

**Comment by seanjreilly** [comment] 2013-08-08 11:17
I've just posted a bug report for this issue to the gradle dev list, and according to them, the problem is that the plugin uses the gradle internal API.

The steer seems to be that gradle plugins shouldn't use the internal api, as it's not backwards compatible.

**Comment by david-resnick** [comment] 2013-08-23 05:49
This issue is duplicated by the more general #44

**Comment by AlanKrueger** [comment] 2013-08-25 20:49
Agreed. Closing in favor of #44.

**Closed as completed** 2013-08-25 20:49 UTC
