### ISSUE TITLE
Batch Script will not work if RPM has been build on Windows

### ISSUE THREAD

**Issue by chilicat** [TrigonicSolutions/gradle-rpm-plugin#35] opened 2013-05-16 11:58 UTC
I noticed if I build the RPM on windows that my shell script do not work on the target system. The reason for that seem to be the CrLF. 

The copy spec allows to specify filter which would take care about it. Here is an example:

```
   import org.apache.tools.ant.filters.*
   from(fileTree('src/bin')) {
        fileMode = 0700
        filter(FixCrLfFilter,
                eol: FixCrLfFilter.CrLf.newInstance('lf'),
                tab: FixCrLfFilter.AddAsisRemove.newInstance('asis'),
                eof: FixCrLfFilter.AddAsisRemove.newInstance('remove'),
                fixlast: true)
    }
```

If I use the filter with the RPM task than I will get an java.lang.UnsupportedOperationException

would it be possible either to provide filters in the rpm task or to do auto CrLf convertions for files.

The gradle plugin is great. Saves me a lot of time. Thanks for that!

**Comment by AlanKrueger** [comment] 2013-05-19 19:16
This looks like a duplicate of [issue 30](https://github.com/TrigonicSolutions/gradle-rpm-plugin/issues/30).

**Closed as completed by AlanKrueger** 2013-05-19 19:16 UTC
